name: Generate ASCII Artwork

on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: List repo files
              run: ls -lstr

            - name: executing shell script
              run:
                chmod +x 
                .github/workflows/script.sh


        